name: Sync to Downstream Repo (demo)

on:
  push:
    branches:
      - main

jobs:
  sync-private:
    runs-on: ubuntu-latest

    env:
      PRIVATE_REPO: Penguin-International-Gurgaon/ai-chatbot-live-demo
      PRIVATE_BRANCH: sync-${{ github.sha }}

    steps:
      - name: Checkout public repo (source)
        uses: actions/checkout@v4

      - name: Checkout private repo (target)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PRIVATE_REPO }}
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          path: private-repo
          ref: main # base branch in private repo

      - name: Copy files to private repo
        run: |
          rsync -av --delete --exclude=".git" ./ ./private-repo/

      - name: Commit & push to new branch in private repo
        run: |
          cd private-repo
          git config user.name "sync-bot"
          git config user.email "bot@penguin-international.com"

          git checkout -b ${{ env.PRIVATE_BRANCH }}
          git add .
          git commit -m "Sync from public repo at ${{ github.sha }}" || echo "Nothing to commit"
          git push origin ${{ env.PRIVATE_BRANCH }}

      - name: Create Pull Request in Private Repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          repository: ${{ env.PRIVATE_REPO }}
          title: "Sync: ${{ github.sha }}"
          body: |
            Auto-generated PR from upstream commit ${{ github.sha }}.
          base: main
          head: ${{ env.PRIVATE_BRANCH }}
